# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\VS\Serial_Port\form1.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(766, 600)
        MainWindow.setMaximumSize(QtCore.QSize(766, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\VS\\Serial_Port\\ICON/net_port_connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 171, 211))
        self.groupBox.setObjectName("groupBox")
        self.comboBox_uart = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_uart.setGeometry(QtCore.QRect(81, 26, 69, 20))
        self.comboBox_uart.setObjectName("comboBox_uart")
        self.comboBox_baud = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_baud.setGeometry(QtCore.QRect(81, 57, 69, 20))
        self.comboBox_baud.setObjectName("comboBox_baud")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_databit = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_databit.setGeometry(QtCore.QRect(81, 88, 69, 20))
        self.comboBox_databit.setObjectName("comboBox_databit")
        self.comboBox_databit.addItem("")
        self.comboBox_databit.addItem("")
        self.comboBox_databit.addItem("")
        self.comboBox_databit.addItem("")
        self.comboBox_polarity = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_polarity.setGeometry(QtCore.QRect(81, 119, 69, 20))
        self.comboBox_polarity.setObjectName("comboBox_polarity")
        self.comboBox_polarity.addItem("")
        self.comboBox_polarity.addItem("")
        self.comboBox_polarity.addItem("")
        self.comboBox_stopbit = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_stopbit.setGeometry(QtCore.QRect(81, 150, 69, 20))
        self.comboBox_stopbit.setObjectName("comboBox_stopbit")
        self.comboBox_stopbit.addItem("")
        self.comboBox_stopbit.addItem("")
        self.comboBox_flowctrl = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_flowctrl.setGeometry(QtCore.QRect(81, 181, 69, 20))
        self.comboBox_flowctrl.setObjectName("comboBox_flowctrl")
        self.comboBox_flowctrl.addItem("")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(20, 30, 38, 171))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 230, 171, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_rcv_ascii = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_rcv_ascii.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.radioButton_rcv_ascii.setObjectName("radioButton_rcv_ascii")
        self.radioButton_rcv_hex = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_rcv_hex.setGeometry(QtCore.QRect(100, 20, 51, 16))
        self.radioButton_rcv_hex.setObjectName("radioButton_rcv_hex")
        self.checkBox_auto_line = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_auto_line.setGeometry(QtCore.QRect(10, 50, 71, 16))
        self.checkBox_auto_line.setObjectName("checkBox_auto_line")
        self.checkBox_display_std = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_display_std.setGeometry(QtCore.QRect(10, 80, 71, 16))
        self.checkBox_display_std.setObjectName("checkBox_display_std")
        self.checkBox_display_time = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_display_time.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.checkBox_display_time.setObjectName("checkBox_display_time")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 380, 171, 121))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_std_hex = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_std_hex.setGeometry(QtCore.QRect(100, 20, 51, 16))
        self.radioButton_std_hex.setObjectName("radioButton_std_hex")
        self.radioButton_std_ascii = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_std_ascii.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.radioButton_std_ascii.setObjectName("radioButton_std_ascii")
        self.checkBox_resend = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_resend.setGeometry(QtCore.QRect(10, 50, 71, 16))
        self.checkBox_resend.setObjectName("checkBox_resend")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox.setGeometry(QtCore.QRect(10, 80, 71, 22))
        self.spinBox.setObjectName("spinBox")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(90, 90, 54, 12))
        self.label_11.setObjectName("label_11")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(200, 20, 451, 351))
        self.textBrowser.setObjectName("textBrowser")
        self.textEdit_get = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_get.setGeometry(QtCore.QRect(200, 380, 451, 121))
        self.textEdit_get.setObjectName("textEdit_get")
        self.btn_send = QtWidgets.QPushButton(self.centralwidget)
        self.btn_send.setGeometry(QtCore.QRect(670, 470, 91, 23))
        self.btn_send.setObjectName("btn_send")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 766, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_start = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("d:\\VS\\Serial_Port\\ICON/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_start.setIcon(icon1)
        self.action_start.setObjectName("action_start")
        self.action_pause = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("d:\\VS\\Serial_Port\\ICON/zt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_pause.setIcon(icon2)
        self.action_pause.setObjectName("action_pause")
        self.action_stop = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("d:\\VS\\Serial_Port\\ICON/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_stop.setIcon(icon3)
        self.action_stop.setObjectName("action_stop")
        self.action_clean = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("d:\\VS\\Serial_Port\\ICON/clean.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_clean.setIcon(icon4)
        self.action_clean.setObjectName("action_clean")
        self.menu.addAction(self.action_start)
        self.menu.addAction(self.action_pause)
        self.menu.addAction(self.action_stop)
        self.menu.addAction(self.action_clean)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.toolBar.addAction(self.action_start)
        self.toolBar.addAction(self.action_pause)
        self.toolBar.addAction(self.action_stop)
        self.toolBar.addAction(self.action_clean)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "串口调试工具ROG"))
        self.groupBox.setTitle(_translate("MainWindow", "串口设置"))
        self.comboBox_baud.setItemText(0, _translate("MainWindow", "2400"))
        self.comboBox_baud.setItemText(1, _translate("MainWindow", "9600"))
        self.comboBox_baud.setItemText(2, _translate("MainWindow", "19200"))
        self.comboBox_baud.setItemText(3, _translate("MainWindow", "38400"))
        self.comboBox_databit.setItemText(0, _translate("MainWindow", "5"))
        self.comboBox_databit.setItemText(1, _translate("MainWindow", "6"))
        self.comboBox_databit.setItemText(2, _translate("MainWindow", "7"))
        self.comboBox_databit.setItemText(3, _translate("MainWindow", "8"))
        self.comboBox_polarity.setItemText(0, _translate("MainWindow", "无"))
        self.comboBox_polarity.setItemText(1, _translate("MainWindow", "偶校验"))
        self.comboBox_polarity.setItemText(2, _translate("MainWindow", "奇校验"))
        self.comboBox_stopbit.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_stopbit.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_flowctrl.setItemText(0, _translate("MainWindow", "无"))
        self.label.setText(_translate("MainWindow", "串口"))
        self.label_2.setText(_translate("MainWindow", "波特率"))
        self.label_3.setText(_translate("MainWindow", "数据位"))
        self.label_4.setText(_translate("MainWindow", "校验位"))
        self.label_9.setText(_translate("MainWindow", "停止位"))
        self.label_10.setText(_translate("MainWindow", "流控"))
        self.groupBox_2.setTitle(_translate("MainWindow", "接受设置"))
        self.radioButton_rcv_ascii.setText(_translate("MainWindow", "ASCII"))
        self.radioButton_rcv_hex.setText(_translate("MainWindow", "HEX"))
        self.checkBox_auto_line.setText(_translate("MainWindow", "自动换行"))
        self.checkBox_display_std.setText(_translate("MainWindow", "显示发送"))
        self.checkBox_display_time.setText(_translate("MainWindow", "显示时间"))
        self.groupBox_3.setTitle(_translate("MainWindow", "发送设置"))
        self.radioButton_std_hex.setText(_translate("MainWindow", "HEX"))
        self.radioButton_std_ascii.setText(_translate("MainWindow", "ASCII"))
        self.checkBox_resend.setText(_translate("MainWindow", "重复发送"))
        self.label_11.setText(_translate("MainWindow", "ms/次"))
        self.btn_send.setText(_translate("MainWindow", "发送"))
        self.menu.setTitle(_translate("MainWindow", "编辑"))
        self.menu_2.setTitle(_translate("MainWindow", "显示"))
        self.menu_3.setTitle(_translate("MainWindow", "工具"))
        self.menu_4.setTitle(_translate("MainWindow", "帮助"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_start.setText(_translate("MainWindow", "开始"))
        self.action_start.setShortcut(_translate("MainWindow", "F6"))
        self.action_pause.setText(_translate("MainWindow", "暂停"))
        self.action_pause.setShortcut(_translate("MainWindow", "F7"))
        self.action_stop.setText(_translate("MainWindow", "停止"))
        self.action_stop.setShortcut(_translate("MainWindow", "F8"))
        self.action_clean.setText(_translate("MainWindow", "清除"))
        self.action_clean.setShortcut(_translate("MainWindow", "F9"))
